// Core Types and Enums for AWS Account Governance Engine

// Scan modes
export type ScanMode = "single-account" | "organization";

// Risk classification
export type RiskLevel = "Low" | "Medium" | "High";

// Advisor types
export type AdvisorType = "SafeCleanupAdvisor" | "PermissionDriftDetector" | "ZombieResourceDetector" | "GovernancePolicyEngine";

// Condition operators for governance policies
export type ConditionOperator =
  | "equals"
  | "not_equals"
  | "greater_than"
  | "less_than"
  | "in"
  | "not_in"
  | "contains"
  | "not_contains"
  | "exists"
  | "not_exists";

// A condition within a governance policy
export interface PolicyCondition {
  property: string;
  operator: ConditionOperator;
  value?: unknown;
}

// A user-defined governance policy
export interface GovernancePolicy {
  policyId: string;
  name: string;
  description: string;
  enabled: boolean;
  resourceType: ResourceType;
  condition: PolicyCondition;
  severity: RiskLevel;
  createdAt: string;
  updatedAt: string;
}

// Resource types the engine can detect
export type ResourceType =
  | "EC2Instance"
  | "EBSVolume"
  | "S3Bucket"
  | "ElasticIP"
  | "LoadBalancer"
  | "SecurityGroup"
  | "IAMUser"
  | "IAMRole"
  | "LambdaFunction"
  | "RDSInstance"
  | "ECSService"
  | "ECSCluster"
  | "NATGateway"
  | "CloudWatchLogGroup"
  | "VPC"
  | "Subnet"
  | "SNSTopic"
  | "SQSQueue"
  | "DynamoDBTable"
  | "CloudFrontDistribution"
  | "AutoScalingGroup"
  | "StepFunction"
  | "CloudFormationStack"
  | "APIGatewayRestAPI"
  | "APIGatewayHttpAPI"
  | "Route53HostedZone"
  | "EFSFileSystem"
  | "ECRRepository"
  | "ElastiCacheCluster"
  | "EventBridgeRule"
  | "KinesisStream"
  | "CognitoUserPool"
  | "SecretsManagerSecret"
  | "ACMCertificate"
  | "KMSKey"
  | "WAFWebACL"
  | "CodePipeline"
  | "CodeBuildProject"
  | "CodeCommitRepo"
  | "AmplifyApp";

// Actions that can be taken on resources
export type ActionType = "terminate" | "stop" | "delete" | "release" | "detach";

// Action execution status
export type ActionStatus = "PENDING" | "IN_PROGRESS" | "SUCCESS" | "FAILED";

// Scan execution status
export type ScanStatus = "IN_PROGRESS" | "COMPLETED" | "FAILED";

// Dependency information for a resource
export interface DependencyInfo {
  resourceId: string;
  resourceType: string;
  relationship: string; // e.g., "snapshot references volume"
}

// Recommendation generated by an advisor
export interface Recommendation {
  recommendationId: string;       // UUID
  scanId: string;                 // Reference to parent scan
  accountId: string;              // AWS account where resource resides
  region: string;                 // AWS region
  advisorType: AdvisorType;
  resourceId: string;             // AWS resource identifier (ARN or ID)
  resourceType: ResourceType;
  issueDescription: string;       // What was detected
  suggestedAction: string;        // What the user should do
  riskLevel: RiskLevel;
  explanation: string;            // Human-readable explanation
  estimatedMonthlySavings: number | null; // null when cost data unavailable
  dependencies: DependencyInfo[]; // Resources that reference this resource
  availableActions: ActionType[]; // Actions that can be taken from dashboard
  createdAt: string;              // ISO 8601 timestamp
}

// Scan error details
export interface ScanError {
  accountId: string;
  region: string;
  resourceType?: string;
  errorCode: string;
  errorMessage: string;
}

// Scan record metadata
export interface ScanRecord {
  scanId: string;                 // UUID
  status: ScanStatus;
  scanMode: ScanMode;
  startTime: string;              // ISO 8601
  endTime?: string;               // ISO 8601
  resourcesEvaluated: number;
  recommendationCount: number;
  accountsScanned: string[];      // List of account IDs scanned
  regionsScanned: string[];       // List of regions scanned
  errors: ScanError[];
}

// Resource action record
export interface ResourceAction {
  actionId: string;               // UUID
  recommendationId: string;       // Reference to recommendation
  userId: string;                 // Identity of user who initiated
  accountId: string;
  region: string;
  resourceId: string;
  resourceType: ResourceType;
  actionType: ActionType;
  status: ActionStatus;
  initiatedAt: string;            // ISO 8601
  completedAt?: string;           // ISO 8601
  result?: string;                // Success message or error details
}

// Lookback period configuration per advisor
export interface LookbackConfig {
  safeCleanupAdvisor: number;     // Days, default 90, range 7-365
  permissionDriftDetector: number; // Days, default 90, range 7-365
  zombieResourceDetector: number;  // Days, default 90, range 7-365
}

// Report configuration
export interface ReportConfig {
  enabled: boolean;
  frequency: "daily" | "weekly" | "monthly";
  recipients: string[];
}

// Account filter for organization mode
export interface AccountFilter {
  includeAccounts?: string[];     // Account IDs to include
  includeOUs?: string[];          // OU IDs to include
  excludeAccounts?: string[];     // Account IDs to exclude
  excludeOUs?: string[];          // OU IDs to exclude
}

// Organization mode configuration
export interface OrganizationConfig {
  managementAccountId: string;
  accountFilter: AccountFilter;
}

// Top-level governance configuration
export interface GovernanceConfig {
  scanMode: ScanMode;
  scanSchedule: string;           // Cron expression
  lookbackPeriods: LookbackConfig;
  regions: string[];              // Empty = all commercial regions
  reportConfig: ReportConfig;
  organizationConfig?: OrganizationConfig;
  crossAccountRoleName: string;   // Default: "GovernanceEngineReadOnlyRole"
}

// --- Resource Dependency Graph Types ---

// Extended resource types for graph-only resources (VPC, Subnet, etc.)
export type GraphResourceType =
  | ResourceType
  | "SubnetGroup"
  | "TargetGroup";

// A single AWS resource represented as a node in the dependency graph
export interface ResourceNode {
  resourceId: string;
  resourceType: GraphResourceType;
  accountId: string;
  region: string;
  displayName: string;
}

// A directed relationship between two resource nodes
export interface DependencyEdge {
  sourceResourceId: string;
  targetResourceId: string;
  relationshipLabel: string;
}

// Full dependency graph for a scan
export interface DependencyGraph {
  scanId: string;
  nodes: ResourceNode[];
  edges: DependencyEdge[];
}

// Error encountered during dependency discovery for a specific resource type
export interface GraphDiscoveryError {
  resourceType: string;
  errorCode: string;
  errorMessage: string;
}

// API response shape for GET /dependency-graph
export interface DependencyGraphResponse {
  scanId: string;
  nodes: ResourceNode[];
  edges: DependencyEdge[];
}

// Result of blast radius calculation for a selected resource
export interface BlastRadiusResult {
  affectedNodes: ResourceNode[];
  affectedByType: Record<string, number>;
  totalAffected: number;
}
